import type { Deployment } from "./types"

export const mockDeployments: Deployment[] = [
  {
    id: "dep-1",
    releaseId: "rel-1",
    environmentId: "env-dev",
    deployedAt: new Date("2024-01-15T10:35:00"),
    actor: "john.doe@example.com",
    status: "success",
    region: "us-east-1",
    requiredSuites: [
      { id: "test-1", name: "Unit Tests - API", status: "passed" },
      { id: "test-2", name: "Workflow Tests - Auth", status: "passed" },
    ],
    optionalSuites: [{ id: "test-5", name: "Integration Tests", status: "passed" }],
    logs: [
      "[10:30:00] Starting deployment pipeline...",
      "[10:30:15] Fetching release artifacts for rel-1",
      "[10:31:00] Validating configuration for env-dev (us-east-1)",
      "[10:31:15] Running Unit Tests - API",
      "[10:31:50] Unit Tests - API: PASSED",
      "[10:32:10] Running Workflow Tests - Auth",
      "[10:32:45] Workflow Tests - Auth: PASSED",
      "[10:33:05] Running Integration Tests",
      "[10:33:40] Integration Tests: PASSED",
      "[10:34:00] All test gates passed. Deploying...",
      "[10:35:00] Deployment completed successfully.",
    ].join("\n"),
  },
  {
    id: "dep-2",
    releaseId: "rel-2",
    environmentId: "env-stage",
    deployedAt: new Date("2024-01-14T16:00:00"),
    actor: "jane.smith@example.com",
    status: "success",
    region: "us-west-2",
    requiredSuites: [
      { id: "test-3", name: "Unit Tests - Database", status: "passed" },
      { id: "test-2", name: "Workflow Tests - Auth", status: "passed" },
    ],
    logs: [
      "[15:50:00] Starting deployment pipeline...",
      "[15:50:15] Fetching release artifacts for rel-2",
      "[15:51:00] Validating configuration for env-stage (us-west-2)",
      "[15:51:20] Running Unit Tests - Database",
      "[15:52:05] Unit Tests - Database: PASSED",
      "[15:52:20] Running Workflow Tests - Auth",
      "[15:53:05] Workflow Tests - Auth: PASSED",
      "[15:53:30] All test gates passed. Deploying...",
      "[16:00:00] Deployment completed successfully.",
    ].join("\n"),
  },
  {
    id: "dep-3",
    releaseId: "rel-2",
    environmentId: "env-prod",
    deployedAt: new Date("2024-01-14T18:30:00"),
    actor: "admin@example.com",
    status: "success",
    region: "us-east-1",
    requiredSuites: [
      { id: "test-1", name: "Unit Tests - API", status: "passed" },
      { id: "test-2", name: "Workflow Tests - Auth", status: "passed" },
      { id: "test-4", name: "Workflow Tests - Payment", status: "passed" },
    ],
    optionalSuites: [{ id: "test-5", name: "Performance Tests", status: "passed" }],
    logs: [
      "[18:20:00] Starting deployment pipeline...",
      "[18:20:20] Fetching release artifacts for rel-2",
      "[18:21:10] Validating configuration for env-prod (us-east-1)",
      "[18:21:25] Running Unit Tests - API",
      "[18:22:00] Unit Tests - API: PASSED",
      "[18:22:15] Running Workflow Tests - Auth",
      "[18:22:55] Workflow Tests - Auth: PASSED",
      "[18:23:10] Running Workflow Tests - Payment",
      "[18:24:05] Workflow Tests - Payment: PASSED",
      "[18:24:30] Running Performance Tests",
      "[18:26:45] Performance Tests: PASSED",
      "[18:27:10] All test gates passed. Deploying...",
      "[18:30:00] Deployment completed successfully.",
    ].join("\n"),
  },
]

